# Generated by Django 4.1 on 2025-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settingsCartas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.CharField(blank=True, max_length=20, null=True)),
                ('Mes', models.CharField(blank=True, max_length=50, null=True)),
                ('Ano', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='settingsDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('ano_actual', models.CharField(blank=True, max_length=4, null=True)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsVentaSincronizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('token', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
