# Generated by Django 4.1 on 2025-04-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettingsCartas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingsDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('ano_actual', models.CharField(blank=True, max_length=4, null=True)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
