# Generated by Django 4.1 on 2025-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettingsCartas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdatos',
            name='url_meses_no_paga',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
