# Generated by Django 4.1 on 2024-06-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPagosTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operation', models.BigIntegerField()),
                ('id_persona', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('Dni', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=255)),
                ('NombreCompleto', models.CharField(max_length=306)),
                ('Nivel', models.CharField(max_length=100)),
                ('Grado', models.CharField(max_length=101)),
                ('Seccion', models.CharField(max_length=100)),
                ('Concepto', models.CharField(max_length=50)),
                ('Mes', models.CharField(max_length=12)),
                ('TipoIngreso', models.CharField(max_length=13)),
                ('ConceptoNumeroMes', models.CharField(max_length=2)),
                ('FechaVencimiento', models.CharField(max_length=10)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('FechaPago', models.DateField()),
                ('NumeroMesPago', models.BigIntegerField()),
                ('LetraMesPago', models.CharField(max_length=12)),
                ('Atrasado', models.CharField(max_length=2)),
                ('DiasAtrasado', models.IntegerField()),
                ('MesesAtraso', models.CharField(max_length=50)),
                ('Apoderado', models.CharField(max_length=250)),
                ('Padre', models.CharField(max_length=550)),
                ('Madre', models.CharField(max_length=550)),
                ('Direccion', models.CharField(max_length=250)),
            ],
        ),
    ]
