# Generated by Django 4.1 on 2024-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0003_rename_diasatrasado_viewpagostable_diasatraso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpagostable',
            name='FechaVencimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
