# Generated by Django 4.1 on 2024-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0005_alter_viewpagostable_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpagostable',
            name='MesesAtraso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
