# Generated by Django 4.1 on 2024-06-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0008_alumnostableapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnostableapi',
            name='Id_alumno',
        ),
    ]
