# Generated by Django 4.1 on 2024-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):
    def run_store_procedures(apps,schema_editor):
        with schema_editor.connection.cursor() as cursor:
            #ejecuta el primer procedimiento almacenado
            cursor.execute("""
                DROP PROCEDURE IF EXISTS GetPagosPorMes;
                """)
            cursor.execute("""
                CREATE PROCEDURE GetPagosPorMes()
                BEGIN
                    SELECT
                        CAST(vpt.ConceptoNumeroMes AS UNSIGNED) AS NumeroMes,
                        vpt.Mes AS Mes,
                        SUM(vpt.Monto) AS Cantidad
                    FROM appMain_viewpagostable AS vpt
                    WHERE vpt.Mes IN ('MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SETIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE')
                    GROUP BY vpt.Mes, vpt.ConceptoNumeroMes
                    ORDER BY NumeroMes;
                END;
                """)
            
            cursor.execute("""
                DROP PROCEDURE IF EXISTS GetPagosPorNivel;
                """)
            cursor.execute("""
                CREATE PROCEDURE GetPagosPorNivel()
                BEGIN
                    SELECT
                        vpt.Nivel AS NIVEL,
                        SUM(vpt.Monto) AS Cantidad
                    FROM appMain_viewpagostable AS vpt
                    GROUP BY vpt.Nivel;
                END;
                """)
            
    dependencies = [
        ('appMain', '0009_remove_alumnostableapi_id_alumno'),
    ]

    operations = [
        migrations.RunPython(run_store_procedures),
    ]

    